services:
  vsserver:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        UID: 1002
        GUID: 1002
    ports:
      - 42420:42420
    volumes:
      - ./data:/home/vintagestory/data
    restart: unless-stopped
    deploy:
      restart_policy:
        condition: "on-failure"
        delay: 5s
        max_attempts: 3
        window: 120s
    tty: true
    stdin_open: true
